// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'ss_node_input.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

SsNodeInput _$SsNodeInputFromJson(Map<String, dynamic> json) => SsNodeInput(
  id: (json['id'] as num?)?.toInt(),
  nodeName: json['node_name'] as String,
  nodeConfig: NodeConfig.fromJson(json['node_config'] as Map<String, dynamic>),
  priority: (json['priority'] as num?)?.toInt() ?? 60000,
  isEnable: json['is_enable'] as bool? ?? true,
  iso3166Code:
      $enumDecodeNullable(_$CountryCodeEnumMap, json['iso3166_code']) ??
      CountryCode.ar,
  vpnType:
      $enumDecodeNullable(_$VpnTypeEnumEnumMap, json['vpn_type']) ??
      VpnTypeEnum.vmess,
  nodeRate: json['node_rate'] ?? 1.00,
  nodeLevel: (json['node_level'] as num?)?.toInt() ?? 0,
  isHideNode: json['is_hide_node'] as bool? ?? false,
  createdAt: json['created_at'] == null
      ? null
      : DateTime.parse(json['created_at'] as String),
  updatedAt: json['updated_at'] == null
      ? null
      : DateTime.parse(json['updated_at'] as String),
  nodeInfo: json['node_info'] as String?,
  remark: json['remark'] as String?,
  nodeSpeedLimit: json['node_speed_limit'],
  userGroupHost: json['user_group_host'] == null
      ? null
      : UserGroupHost.fromJson(json['user_group_host'] as Map<String, dynamic>),
);

Map<String, dynamic> _$SsNodeInputToJson(SsNodeInput instance) =>
    <String, dynamic>{
      'id': instance.id,
      'created_at': ?instance.createdAt?.toIso8601String(),
      'updated_at': ?instance.updatedAt?.toIso8601String(),
      'priority': instance.priority,
      'node_name': instance.nodeName,
      'node_config': instance.nodeConfig,
      'is_enable': instance.isEnable,
      'iso3166_code': _$CountryCodeEnumMap[instance.iso3166Code]!,
      'vpn_type': _$VpnTypeEnumEnumMap[instance.vpnType]!,
      'node_rate': instance.nodeRate,
      'node_level': instance.nodeLevel,
      'node_info': ?instance.nodeInfo,
      'remark': ?instance.remark,
      'node_speed_limit': ?instance.nodeSpeedLimit,
      'user_group_host': ?instance.userGroupHost,
      'is_hide_node': instance.isHideNode,
    };

const _$CountryCodeEnumMap = {
  CountryCode.af: 'AF',
  CountryCode.ax: 'AX',
  CountryCode.al: 'AL',
  CountryCode.dz: 'DZ',
  CountryCode.valueAs: 'AS',
  CountryCode.ad: 'AD',
  CountryCode.ao: 'AO',
  CountryCode.ai: 'AI',
  CountryCode.aq: 'AQ',
  CountryCode.ag: 'AG',
  CountryCode.ar: 'AR',
  CountryCode.am: 'AM',
  CountryCode.aw: 'AW',
  CountryCode.au: 'AU',
  CountryCode.at: 'AT',
  CountryCode.az: 'AZ',
  CountryCode.bs: 'BS',
  CountryCode.bh: 'BH',
  CountryCode.bd: 'BD',
  CountryCode.bb: 'BB',
  CountryCode.by: 'BY',
  CountryCode.be: 'BE',
  CountryCode.bz: 'BZ',
  CountryCode.bj: 'BJ',
  CountryCode.bm: 'BM',
  CountryCode.bt: 'BT',
  CountryCode.bo: 'BO',
  CountryCode.bq: 'BQ',
  CountryCode.ba: 'BA',
  CountryCode.bw: 'BW',
  CountryCode.bv: 'BV',
  CountryCode.br: 'BR',
  CountryCode.io: 'IO',
  CountryCode.bn: 'BN',
  CountryCode.bg: 'BG',
  CountryCode.bf: 'BF',
  CountryCode.bi: 'BI',
  CountryCode.cv: 'CV',
  CountryCode.kh: 'KH',
  CountryCode.cm: 'CM',
  CountryCode.ca: 'CA',
  CountryCode.ky: 'KY',
  CountryCode.cf: 'CF',
  CountryCode.td: 'TD',
  CountryCode.cl: 'CL',
  CountryCode.cn: 'CN',
  CountryCode.cx: 'CX',
  CountryCode.cc: 'CC',
  CountryCode.co: 'CO',
  CountryCode.km: 'KM',
  CountryCode.cg: 'CG',
  CountryCode.cd: 'CD',
  CountryCode.ck: 'CK',
  CountryCode.cr: 'CR',
  CountryCode.ci: 'CI',
  CountryCode.hr: 'HR',
  CountryCode.cu: 'CU',
  CountryCode.cw: 'CW',
  CountryCode.cy: 'CY',
  CountryCode.cz: 'CZ',
  CountryCode.dk: 'DK',
  CountryCode.dj: 'DJ',
  CountryCode.dm: 'DM',
  CountryCode.valueDo: 'DO',
  CountryCode.ec: 'EC',
  CountryCode.eg: 'EG',
  CountryCode.sv: 'SV',
  CountryCode.gq: 'GQ',
  CountryCode.er: 'ER',
  CountryCode.ee: 'EE',
  CountryCode.sz: 'SZ',
  CountryCode.et: 'ET',
  CountryCode.fk: 'FK',
  CountryCode.fo: 'FO',
  CountryCode.fj: 'FJ',
  CountryCode.fi: 'FI',
  CountryCode.fr: 'FR',
  CountryCode.gf: 'GF',
  CountryCode.pf: 'PF',
  CountryCode.tf: 'TF',
  CountryCode.ga: 'GA',
  CountryCode.gm: 'GM',
  CountryCode.ge: 'GE',
  CountryCode.de: 'DE',
  CountryCode.gh: 'GH',
  CountryCode.gi: 'GI',
  CountryCode.gr: 'GR',
  CountryCode.gl: 'GL',
  CountryCode.gd: 'GD',
  CountryCode.gp: 'GP',
  CountryCode.gu: 'GU',
  CountryCode.gt: 'GT',
  CountryCode.gg: 'GG',
  CountryCode.gn: 'GN',
  CountryCode.gw: 'GW',
  CountryCode.gy: 'GY',
  CountryCode.ht: 'HT',
  CountryCode.hm: 'HM',
  CountryCode.va: 'VA',
  CountryCode.hn: 'HN',
  CountryCode.hk: 'HK',
  CountryCode.hu: 'HU',
  CountryCode.valueIs: 'IS',
  CountryCode.valueIn: 'IN',
  CountryCode.id: 'ID',
  CountryCode.ir: 'IR',
  CountryCode.iq: 'IQ',
  CountryCode.ie: 'IE',
  CountryCode.im: 'IM',
  CountryCode.il: 'IL',
  CountryCode.it: 'IT',
  CountryCode.jm: 'JM',
  CountryCode.jp: 'JP',
  CountryCode.je: 'JE',
  CountryCode.jo: 'JO',
  CountryCode.kz: 'KZ',
  CountryCode.ke: 'KE',
  CountryCode.ki: 'KI',
  CountryCode.kp: 'KP',
  CountryCode.kr: 'KR',
  CountryCode.kw: 'KW',
  CountryCode.kg: 'KG',
  CountryCode.la: 'LA',
  CountryCode.lv: 'LV',
  CountryCode.lb: 'LB',
  CountryCode.ls: 'LS',
  CountryCode.lr: 'LR',
  CountryCode.ly: 'LY',
  CountryCode.li: 'LI',
  CountryCode.lt: 'LT',
  CountryCode.lu: 'LU',
  CountryCode.mo: 'MO',
  CountryCode.mg: 'MG',
  CountryCode.mw: 'MW',
  CountryCode.my: 'MY',
  CountryCode.mv: 'MV',
  CountryCode.ml: 'ML',
  CountryCode.mt: 'MT',
  CountryCode.mh: 'MH',
  CountryCode.mq: 'MQ',
  CountryCode.mr: 'MR',
  CountryCode.mu: 'MU',
  CountryCode.yt: 'YT',
  CountryCode.mx: 'MX',
  CountryCode.fm: 'FM',
  CountryCode.md: 'MD',
  CountryCode.mc: 'MC',
  CountryCode.mn: 'MN',
  CountryCode.me: 'ME',
  CountryCode.ms: 'MS',
  CountryCode.ma: 'MA',
  CountryCode.mz: 'MZ',
  CountryCode.mm: 'MM',
  CountryCode.na: 'NA',
  CountryCode.nr: 'NR',
  CountryCode.np: 'NP',
  CountryCode.nl: 'NL',
  CountryCode.nc: 'NC',
  CountryCode.nz: 'NZ',
  CountryCode.ni: 'NI',
  CountryCode.ne: 'NE',
  CountryCode.ng: 'NG',
  CountryCode.nu: 'NU',
  CountryCode.nf: 'NF',
  CountryCode.mk: 'MK',
  CountryCode.mp: 'MP',
  CountryCode.no: 'NO',
  CountryCode.om: 'OM',
  CountryCode.pk: 'PK',
  CountryCode.pw: 'PW',
  CountryCode.ps: 'PS',
  CountryCode.pa: 'PA',
  CountryCode.pg: 'PG',
  CountryCode.py: 'PY',
  CountryCode.pe: 'PE',
  CountryCode.ph: 'PH',
  CountryCode.pn: 'PN',
  CountryCode.pl: 'PL',
  CountryCode.pt: 'PT',
  CountryCode.pr: 'PR',
  CountryCode.qa: 'QA',
  CountryCode.re: 'RE',
  CountryCode.ro: 'RO',
  CountryCode.ru: 'RU',
  CountryCode.rw: 'RW',
  CountryCode.bl: 'BL',
  CountryCode.sh: 'SH',
  CountryCode.kn: 'KN',
  CountryCode.lc: 'LC',
  CountryCode.mf: 'MF',
  CountryCode.pm: 'PM',
  CountryCode.vc: 'VC',
  CountryCode.ws: 'WS',
  CountryCode.sm: 'SM',
  CountryCode.st: 'ST',
  CountryCode.sa: 'SA',
  CountryCode.sn: 'SN',
  CountryCode.rs: 'RS',
  CountryCode.sc: 'SC',
  CountryCode.sl: 'SL',
  CountryCode.sg: 'SG',
  CountryCode.sx: 'SX',
  CountryCode.sk: 'SK',
  CountryCode.si: 'SI',
  CountryCode.sb: 'SB',
  CountryCode.so: 'SO',
  CountryCode.za: 'ZA',
  CountryCode.gs: 'GS',
  CountryCode.ss: 'SS',
  CountryCode.es: 'ES',
  CountryCode.lk: 'LK',
  CountryCode.sd: 'SD',
  CountryCode.sr: 'SR',
  CountryCode.sj: 'SJ',
  CountryCode.se: 'SE',
  CountryCode.ch: 'CH',
  CountryCode.sy: 'SY',
  CountryCode.tw: 'TW',
  CountryCode.tj: 'TJ',
  CountryCode.tz: 'TZ',
  CountryCode.th: 'TH',
  CountryCode.tl: 'TL',
  CountryCode.tg: 'TG',
  CountryCode.tk: 'TK',
  CountryCode.to: 'TO',
  CountryCode.tt: 'TT',
  CountryCode.tn: 'TN',
  CountryCode.tr: 'TR',
  CountryCode.tm: 'TM',
  CountryCode.tc: 'TC',
  CountryCode.tv: 'TV',
  CountryCode.ug: 'UG',
  CountryCode.ua: 'UA',
  CountryCode.ae: 'AE',
  CountryCode.gb: 'GB',
  CountryCode.um: 'UM',
  CountryCode.us: 'US',
  CountryCode.uy: 'UY',
  CountryCode.uz: 'UZ',
  CountryCode.vu: 'VU',
  CountryCode.ve: 'VE',
  CountryCode.vn: 'VN',
  CountryCode.vg: 'VG',
  CountryCode.vi: 'VI',
  CountryCode.wf: 'WF',
  CountryCode.eh: 'EH',
  CountryCode.ye: 'YE',
  CountryCode.zm: 'ZM',
  CountryCode.zw: 'ZW',
};

const _$VpnTypeEnumEnumMap = {
  VpnTypeEnum.placeholder: 'placeholder',
  VpnTypeEnum.http: 'http',
  VpnTypeEnum.socks5: 'socks5',
  VpnTypeEnum.vless: 'vless',
  VpnTypeEnum.vmess: 'vmess',
  VpnTypeEnum.trojan: 'trojan',
  VpnTypeEnum.tuic: 'tuic',
  VpnTypeEnum.juicity: 'juicity',
  VpnTypeEnum.naive: 'naive',
  VpnTypeEnum.shadowsocks: 'shadowsocks',
  VpnTypeEnum.shadowsocksr: 'shadowsocksr',
  VpnTypeEnum.hysteria2: 'hysteria2',
};
